spring:
  application:
    name: portfolio-demo
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/portfolioDB

logging:
  level:
    root: INFO
    sql: DEBUG
    projects.portfoliodemo: DEBUG
